networks:
  solar-network:
    name: solar-network

services:
  postgres-db:
    image: postgres:alpine
    container_name: postgres-db
    restart: always
    networks:
      - solar-network
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    shm_size: 256MB
    environment:
      POSTGRES_DB: POSTGRES_DB_NAME
      POSTGRES_USER: POSTGRES_USERNAME
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U POSTGRES_USERNAME -d POSTGRES_DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M

  postgres-admin:
    image: adminer
    container_name: postgres-admin
    restart: always
    networks:
      - solar-network
    ports:
      - 9999:8080

  redis-db:
    image: redis:alpine
    container_name: redis-db
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    networks:
      - solar-network
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 128M

  solarstorm-bot:
    build: ..
    container_name: solarstorm-bot
    restart: always
    networks:
      - solar-network
    volumes:
      - ./config.json:/app/config.json
      - ./logs:/app/logs
